name: irep
image: ubuntu-14-04-x64
min_size: 1gb
config:
  #cloud-config
  users:
    - name: brick
      groups: sudo
      shell: /bin/bash
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
  packages:
    - git
  runcmd:
    - cd /home/brick && git clone git://github.com/LilCub/irep.git && cd irep && npm install && bash build/ubuntu/14.04/provision.sh
